package projecEuler;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

public class EvenFibbNumbers {

	public static void main(String[] args)
	{
		int a = 0,
			b = 1,
			c = 0,
			sumEven = 0;
		
		for(int x = 1; x <= Double.POSITIVE_INFINITY; ++x)
		{
			c = a + b;			
			if(c < 4000000)
			{
				System.out.println(c);
				a = b;
				b = c;
				
				if(c % 2 == 0)
					sumEven += c;
			}
			else
			{
				System.out.println("Sum of even-valued terms: "+sumEven);
				break;
			}
		}
	}

	public static int fibb(int number)
	{
		if(number == 0)
			return 0;
		else if(number == 1)
			return 1;
		else			//	3 - 1			3 - 2 = 1
			return fibb(number - 1) + fibb(number - 2);
	}
}
